### ISSUE TITLE
running stretch_install_nonfactory.sh and picking `no` in "continue with install y/n" still tries to install stuff

### ISSUE THREAD

**Issue by soumith** [hello-robot/stretch_install#16]
Running this script https://github.com/hello-robot/stretch_install/blob/dev/install_20.04/factory/stretch_install_nonfactory.sh and in the first option where it asks you to enter the `xxxx` in `stretch-re1-xxxx`, I made a mistake.
It then asks to continue install y/n.
I pressed `n`, but it still continued to install some packages.

it's possible that this is because this script `stretch_install_nonfactory.sh` doesn't check for error codes.
A patch might be to add a `set -e` at the top of this script

**Comment by hello-binit** [comment]
Thanks @soumith! A fix has been merged in.
