### ISSUE TITLE
Installation gets stuck at “waiting to get online ….” message

### ISSUE THREAD

**Issue by hello-fazil** [hello-robot/stretch_install#33]
The installation gets stuck at `“waiting to get online ….”` message which is printed from the [stretch_initial_setup.sh#L69:L74](https://github.com/hello-robot/stretch_install/blob/master/factory/20.04/stretch_initial_setup.sh#L69:L74).

**Comment by hello-chintan** [comment]
@hello-fazil this is because you need to be connected to the internet to download packages before performing the install.
