### ISSUE TITLE
Unmet dependency of realsense_camera on galactic

### ISSUE THREAD

**Issue by benoit-robotics** [hello-robot/stretch_install#43]
The package realsense_camera has a new dependency called "launch_testing" https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/package.xml that isn't available on galactic. Thus it makes the installation script fail. One workaround would be to clone an older version of the package instead of the tip of the ros2-development branch.

**Comment by hello-chintan** [comment]
Hey @benoit-robotics, I apologize for the late response. The launch_testing key is now ignored by rosdep in Galactic. Check commit https://github.com/hello-robot/stretch_install/commit/162e96ab97120b1333c50dfae7ef95e56fcb88d9.
