### ISSUE TITLE
No stretch-re1-2000 file in my home folder

### ISSUE THREAD

**Issue by jie0530** [hello-robot/stretch_install#53]
Hello, dear developer, when i run the script `./stretch_new_robot_install.sh` to install stretch, i cannot find `stretch-re1-2000` folder in my home folder or in the `stretch_user` folder.

```
./stretch_new_robot_install.sh 
#############################################
STARTING NEW ROBOT INSTALL
#############################################
WARNING: Run this installation for fresh Ubuntu installs only.
Checking ~/.bashrc doesn't already define HELLO_FLEET_ID...
Plug in charger & attach clip-clamp. Ready to proceed (y/n)? y
1) stretch-re1
2) stretch-re2
3) stretch-se3
Select model type: 1
Selected model: stretch-re1
Enter fleet id xxxx for stretch-re1-xxxx> 2000
HELLO_FLEET_ID will be stretch-re1-2000. Proceed with installation (y/n)? y
Checking Stretch Install cloned to right place...
Checking robot calibration data in home folder...
Expecting robot calibration stretch-re1-2000 to be present in the the home folder. Exiting.

#############################################
FAILURE. INSTALLATION DID NOT COMPLETE.
Look at the troubleshooting guide for solutions to common issues: https://docs.hello-robot.com/0.2/stretch-install/docs/robot_install#troubleshooting
or contact Hello Robot support and include /home/mrips/stretch_user/log/stretch_install_202312242313/stretch_robot_install_logs.zip
#############################################
```
It's possible that the stretch-re1-2000 folder is supposed to be generated by running the RE1_migrate_params.py script, but an error occurred: `Robot parameters not found. Unable to migrate. Please contact Hello Robot support for more information. ` 
I also cannot find the yaml files as follows in my stretch_user folder: 
```
stretch_user_params.yaml
stretch_configuration_params.yaml
```

I look forward to your response, thank you very much.

**Comment by hello-binit** [comment]
Hello @jie0530, the `stretch-yyy-xxxx` folder contains robot calibration data unique to your Stretch robot. It is not generated by the migration tool. You can log in to the default account on your Stretch and find your robot's calibration directory in the "~/stretch_user" folder. More details [available here](https://github.com/hello-robot/stretch_install/blob/master/docs/robot_install.md#back-up-robot-configuration-data).
