### ISSUE TITLE
ament_ws for 20.04? 

### ISSUE THREAD

**Issue by JanusMaple** [hello-robot/stretch_install#58]
I am trying to add a new workspace following this guide: https://docs.hello-robot.com/0.2/stretch-install/docs/ros_workspace/, which says that I can have both **catkin_ws** and **ament_ws** in 20.04 system. However, I can not find `stretch_create_ament_workspace.sh` in the folder **factory\20.04**. It seems that we only have `stretch_create_ament_workspace.sh` in 22.04? How can I create a ros2 galactic workspace on 20.04 system?

**Comment by hello-binit** [comment]
Hi @JanusMaple, that script was removed because ROS 2 Galactic is "end of life". It was deprecated Dec 9th, 2022 according to ROS 2's [distributions chart](https://docs.ros.org/en/rolling/Releases.html). We're going to supporting ROS 2 Humble in Ubuntu 22.04.
