### ISSUE TITLE
Librealsense install failure on fresh Ubuntu 22.04

### ISSUE THREAD

**Issue by hello-fazil** [hello-robot/stretch_install#65]
The `stretch_install_system.sh` script errors out while trying to install `librealsense*` packages for a fresh Ubunut 22.04.
Snippet from log file stretch_system_install.txt
```
###########################################
INSTALLATION OF INTEL D435i
###########################################
Register the librealsense APT server's public key
Add the librealsense APT server to the list of APT repositories
Remove old records in case of upgrading
Apt update
Install librealsense2 packages
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Snippet from log file stretch_install_system.XXXXXXXX_redirected.txt
```
Loading the modified modules into kernel...modprobe: FATAL: Module videodev is in use.
dpkg: error processing package librealsense2-dkms (--configure):
 installed librealsense2-dkms package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.6) ...
Errors were encountered while processing:
 librealsense2-dkms
```

**Comment by hello-fazil** [comment]
I found a temporary solution through this thread https://github.com/IntelRealSense/librealsense/issues/11106
I had to purge the librealsense packages and then reinstall 
```
dpkg -l | grep "realsense" | cut -d " " -f 3 | xargs sudo dpkg --purge
```

**Comment by sam-tj** [comment]
Hi,
I have the same issue. For me, I cannot remove the package as well. 

Any hints to fix this?

OS: 22.04
Kernel: 6.5.0-18

**Comment by hello-binit** [comment]
@hello-fazil Is this solved with https://github.com/hello-robot/stretch_install/commit/5cba1f771d35978b0ee9246a3bd734ac3a29eb28?
